CREATE TABLE MURUGAN (
    VEEDU INTEGER PRIMARY KEY NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    STATUS VARCHAR(10) NOT NULL
);
INSERT INTO MURUGAN (VEEDU,NAME,STATUS) VALUES (1,"THIRUPPARANKUNDRAM",'YES'),
(2,'THIRUCENDUR','YES'),
(3,'PALANI','YES'),
(4,'SWAMIMALAI','NO'),
(5,'THIRUTHANI','NO'),
(6,'PALAMUTHIRCHOLAI','YES');
SELECT * FROM MURUGAN;
SELECT STATUS,COUNT(STATUS) AS COUNT FROM MURUGAN GROUP BY STATUS;
ALTER TABLE MURUGAN ADD COLUMN NUMBER INTEGER;
SELECT * FROM MURUGAN WHERE NAME LIKE "THIRU%";
SELECT * FROM MURUGAN WHERE VEEDU BETWEEN 2 AND 5;
SELECT * FROM MURUGAN ORDER BY VEEDU DESC;
UPDATE MURUGAN SET NUMBER=10 WHERE VEEDU=4;
UPDATE MURUGAN SET NUMBER=20 WHERE VEEDU=5;
UPDATE MURUGAN SET NUMBER=30 WHERE VEEDU=6;
UPDATE MURUGAN SET NUMBER=40 WHERE VEEDU=1;
UPDATE MURUGAN SET NUMBER=50 WHERE VEEDU=3;
UPDATE MURUGAN SET NUMBER=60 WHERE VEEDU=2;
SELECT * FROM MURUGAN;
SELECT LENGTH(NAME) AS LENGTH FROM MURUGAN;
SELECT UCASE(NAME) FROM MURUGAN;
